[package]
name = "MyBeagerTracker_back"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "3.0.0"
serde = { version = "1.0", features = ["derive"] }
uuid = "0.8.2"